{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"machine_shape":"hm","authorship_tag":"ABX9TyM0kPPVNtc5oEHQMhrIkeah"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"},"accelerator":"GPU","gpuClass":"premium"},"cells":[{"cell_type":"code","execution_count":1,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"oFN8uXEuLwug","executionInfo":{"status":"ok","timestamp":1666505350997,"user_tz":-540,"elapsed":18927,"user":{"displayName":"정현","userId":"07273060898890773545"}},"outputId":"40ff62d4-8970-4f84-9b87-714aefa0f9e2"},"outputs":[{"output_type":"stream","name":"stdout","text":["Mounted at /gdrive\n"]}],"source":["from google.colab import drive\n","drive.mount('/gdrive')"]},{"cell_type":"code","source":["import os\n","\n","os.getcwd()"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":35},"id":"vaDSH2v2Nbq9","executionInfo":{"status":"ok","timestamp":1666501120089,"user_tz":-540,"elapsed":6,"user":{"displayName":"정현","userId":"07273060898890773545"}},"outputId":"306b202d-fab4-4155-b01f-302e03ef9a56"},"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["'/content'"],"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"}},"metadata":{},"execution_count":2}]},{"cell_type":"code","source":["function ClickConnect(){\n","console.log(\"Working\"); \n","document.querySelector(\"colab-toolbar-button\").click() \n","}setInterval(ClickConnect, 1800000)"],"metadata":{"id":"qAwWxcXcTyLd"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["!python /gdrive/MyDrive/Colab\\ Notebooks/main.py --root /gdrive/MyDrive/Colab\\ Notebooks --config train/rjh/case1/case1.yaml"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"N15pmcH8MV-8","executionInfo":{"status":"ok","timestamp":1666505418205,"user_tz":-540,"elapsed":65224,"user":{"displayName":"정현","userId":"07273060898890773545"}},"outputId":"4dbf9f53-4bd1-4fa5-f800-2971854603f9"},"execution_count":2,"outputs":[{"output_type":"stream","name":"stdout","text":["Found 1120 files belonging to 2 classes.\n","2022-10-23 06:09:30.209865: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.\n","Found 50 files belonging to 2 classes.\n","Downloading data from https://storage.googleapis.com/keras-applications/efficientnetb3_notop.h5\n","43941136/43941136 [==============================] - 1s 0us/step\n","Model: \"my_model\"\n","_________________________________________________________________\n"," Layer (type)                Output Shape              Param #   \n","=================================================================\n"," efficientnetb3 (Functional)  (None, 1536)             10783535  \n","                                                                 \n"," dense (Dense)               multiple                  184440    \n","                                                                 \n"," dense_1 (Dense)             multiple                  14520     \n","                                                                 \n"," dense_2 (Dense)             multiple                  242       \n","                                                                 \n","=================================================================\n","Total params: 10,982,737\n","Trainable params: 10,895,434\n","Non-trainable params: 87,303\n","_________________________________________________________________\n","fold 1, epoch 1 / 50\n","  0/112 [..................................................] - ETA: 0s - loss: 0.0000e+00 - accuracy: 0.0000e+00 - def_recall: 0.0000e+00 - ok_recall: 0.0000e+00 - f1: 0.0000e+00 - ok_f1: 0.0000e+00/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1082: UserWarning: \"`binary_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?\"\n","  return dispatch_target(*args, **kwargs)\n","2022-10-23 06:10:06.614774: W tensorflow/core/common_runtime/bfc_allocator.cc:290] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.26GiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be performance gains if more memory were available.\n","2022-10-23 06:10:06.614830: W tensorflow/core/common_runtime/bfc_allocator.cc:290] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.26GiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be performance gains if more memory were available.\n","2022-10-23 06:10:16.625714: W tensorflow/core/common_runtime/bfc_allocator.cc:479] Allocator (GPU_0_bfc) ran out of memory trying to allocate 165.8KiB (rounded to 169728)requested by op my_model/efficientnetb3/block5d_se_squeeze/Mean\n","If the cause is memory fragmentation maybe the environment variable 'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation. \n","Current allocation summary follows.\n","Current allocation summary follows.\n","2022-10-23 06:10:16.626997: W tensorflow/core/common_runtime/bfc_allocator.cc:491] ****************************************************************************************************\n","2022-10-23 06:10:16.630985: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at reduction_ops_common.h:183 : RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[42432] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n","Traceback (most recent call last):\n","  File \"/gdrive/MyDrive/Colab Notebooks/main.py\", line 96, in <module>\n","    trainer.train(img, lab)\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n","    raise e.with_traceback(filtered_tb) from None\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py\", line 55, in quick_execute\n","    inputs, attrs, num_outputs)\n","tensorflow.python.framework.errors_impl.ResourceExhaustedError: Graph execution error:\n","\n","Detected at node 'my_model/efficientnetb3/block5d_se_squeeze/Mean' defined at (most recent call last):\n","    File \"/gdrive/MyDrive/Colab Notebooks/main.py\", line 96, in <module>\n","      trainer.train(img, lab)\n","    File \"/gdrive/MyDrive/Colab Notebooks/utils/trainer.py\", line 48, in train\n","      preds: tf.Tensor = self._model(images, training=True)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/training.py\", line 490, in __call__\n","      return super().__call__(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py\", line 1014, in __call__\n","      outputs = call_fn(inputs, *args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/gdrive/MyDrive/Colab Notebooks/train/rjh/model/mymodel.py\", line 15, in call\n","      x = self.base(x)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/training.py\", line 490, in __call__\n","      return super().__call__(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py\", line 1014, in __call__\n","      outputs = call_fn(inputs, *args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py\", line 459, in call\n","      inputs, training=training, mask=mask)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n","      outputs = node.layer(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py\", line 1014, in __call__\n","      outputs = call_fn(inputs, *args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/layers/pooling/global_average_pooling2d.py\", line 73, in call\n","      return backend.mean(inputs, axis=[1, 2], keepdims=self.keepdims)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/backend.py\", line 2667, in mean\n","      return tf.reduce_mean(x, axis, keepdims)\n","Node: 'my_model/efficientnetb3/block5d_se_squeeze/Mean'\n","Detected at node 'my_model/efficientnetb3/block5d_se_squeeze/Mean' defined at (most recent call last):\n","    File \"/gdrive/MyDrive/Colab Notebooks/main.py\", line 96, in <module>\n","      trainer.train(img, lab)\n","    File \"/gdrive/MyDrive/Colab Notebooks/utils/trainer.py\", line 48, in train\n","      preds: tf.Tensor = self._model(images, training=True)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/training.py\", line 490, in __call__\n","      return super().__call__(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py\", line 1014, in __call__\n","      outputs = call_fn(inputs, *args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/gdrive/MyDrive/Colab Notebooks/train/rjh/model/mymodel.py\", line 15, in call\n","      x = self.base(x)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/training.py\", line 490, in __call__\n","      return super().__call__(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py\", line 1014, in __call__\n","      outputs = call_fn(inputs, *args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py\", line 459, in call\n","      inputs, training=training, mask=mask)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n","      outputs = node.layer(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py\", line 1014, in __call__\n","      outputs = call_fn(inputs, *args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/layers/pooling/global_average_pooling2d.py\", line 73, in call\n","      return backend.mean(inputs, axis=[1, 2], keepdims=self.keepdims)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/backend.py\", line 2667, in mean\n","      return tf.reduce_mean(x, axis, keepdims)\n","Node: 'my_model/efficientnetb3/block5d_se_squeeze/Mean'\n","2 root error(s) found.\n","  (0) RESOURCE_EXHAUSTED:  OOM when allocating tensor with shape[42432] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n","\t [[{{node my_model/efficientnetb3/block5d_se_squeeze/Mean}}]]\n","Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n","\n","\t [[assert_less_equal_1/Assert/AssertGuard/pivot_f/_43/_61]]\n","Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n","\n","  (1) RESOURCE_EXHAUSTED:  OOM when allocating tensor with shape[42432] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n","\t [[{{node my_model/efficientnetb3/block5d_se_squeeze/Mean}}]]\n","Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n","\n","0 successful operations.\n","0 derived errors ignored. [Op:__inference_train_35614]\n"]}]},{"cell_type":"code","source":[],"metadata":{"id":"YNG4W35gNYr9"},"execution_count":null,"outputs":[]}]}