{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"machine_shape":"hm","authorship_tag":"ABX9TyM0kPPVNtc5oEHQMhrIkeah"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"},"accelerator":"GPU","gpuClass":"premium"},"cells":[{"cell_type":"code","execution_count":1,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"oFN8uXEuLwug","executionInfo":{"status":"ok","timestamp":1666501120088,"user_tz":-540,"elapsed":15317,"user":{"displayName":"정현","userId":"07273060898890773545"}},"outputId":"f129af5c-406d-4bcc-e7ba-5fac5db0290b"},"outputs":[{"output_type":"stream","name":"stdout","text":["Mounted at /gdrive\n"]}],"source":["from google.colab import drive\n","drive.mount('/gdrive')"]},{"cell_type":"code","source":["import os\n","\n","os.getcwd()"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":35},"id":"vaDSH2v2Nbq9","executionInfo":{"status":"ok","timestamp":1666501120089,"user_tz":-540,"elapsed":6,"user":{"displayName":"정현","userId":"07273060898890773545"}},"outputId":"306b202d-fab4-4155-b01f-302e03ef9a56"},"execution_count":2,"outputs":[{"output_type":"execute_result","data":{"text/plain":["'/content'"],"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"}},"metadata":{},"execution_count":2}]},{"cell_type":"code","source":["function ClickConnect(){\n","console.log(\"Working\"); \n","document.querySelector(\"colab-toolbar-button\").click() \n","}setInterval(ClickConnect, 1800000)"],"metadata":{"id":"qAwWxcXcTyLd"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["!python /gdrive/MyDrive/Colab\\ Notebooks/main.py --root /gdrive/MyDrive/Colab\\ Notebooks --config train/rjh/case1/case1.yaml"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"N15pmcH8MV-8","executionInfo":{"status":"ok","timestamp":1666501182819,"user_tz":-540,"elapsed":62735,"user":{"displayName":"정현","userId":"07273060898890773545"}},"outputId":"87bdc298-1d34-4e9a-d8e9-385f2e41ffe0"},"execution_count":3,"outputs":[{"output_type":"stream","name":"stdout","text":["Found 1120 files belonging to 2 classes.\n","2022-10-23 04:58:55.437549: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.\n","Found 50 files belonging to 2 classes.\n","Downloading data from https://storage.googleapis.com/keras-applications/efficientnetb3_notop.h5\n","43941136/43941136 [==============================] - 0s 0us/step\n","fold 1, epoch 1 / 50\n","  0/112 [..................................................] - ETA: 0s - loss: 0.0000e+00 - accuracy: 0.0000e+00 - def_recall: 0.0000e+00 - ok_recall: 0.0000e+00 - f1: 0.0000e+00 - ok_f1: 0.0000e+00/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1082: UserWarning: \"`binary_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?\"\n","  return dispatch_target(*args, **kwargs)\n","2022-10-23 04:59:24.478910: W tensorflow/core/common_runtime/bfc_allocator.cc:290] Allocator (GPU_0_bfc) ran out of memory trying to allocate 885.87MiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be performance gains if more memory were available.\n","2022-10-23 04:59:34.484691: W tensorflow/core/common_runtime/bfc_allocator.cc:479] Allocator (GPU_0_bfc) ran out of memory trying to allocate 27.61MiB (rounded to 28953600)requested by op my_model/efficientnetb3/block6f_expand_conv/Conv2D\n","If the cause is memory fragmentation maybe the environment variable 'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation. \n","Current allocation summary follows.\n","Current allocation summary follows.\n","2022-10-23 04:59:34.485994: W tensorflow/core/common_runtime/bfc_allocator.cc:491] ****************************************************************************************************\n","2022-10-23 04:59:34.490803: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:685 : RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[52,1392,10,10] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n","Traceback (most recent call last):\n","  File \"/gdrive/MyDrive/Colab Notebooks/main.py\", line 93, in <module>\n","    trainer.train(img, lab)\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/traceback_utils.py\", line 153, in error_handler\n","    raise e.with_traceback(filtered_tb) from None\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py\", line 55, in quick_execute\n","    inputs, attrs, num_outputs)\n","tensorflow.python.framework.errors_impl.ResourceExhaustedError: Graph execution error:\n","\n","Detected at node 'my_model/efficientnetb3/block6f_expand_conv/Conv2D' defined at (most recent call last):\n","    File \"/gdrive/MyDrive/Colab Notebooks/main.py\", line 93, in <module>\n","      trainer.train(img, lab)\n","    File \"/gdrive/MyDrive/Colab Notebooks/utils/trainer.py\", line 48, in train\n","      preds: tf.Tensor = self._model(images, training=True)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/training.py\", line 490, in __call__\n","      return super().__call__(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py\", line 1014, in __call__\n","      outputs = call_fn(inputs, *args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/gdrive/MyDrive/Colab Notebooks/train/rjh/model/mymodel.py\", line 15, in call\n","      x = self.base(x)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/training.py\", line 490, in __call__\n","      return super().__call__(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py\", line 1014, in __call__\n","      outputs = call_fn(inputs, *args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py\", line 459, in call\n","      inputs, training=training, mask=mask)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n","      outputs = node.layer(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py\", line 1014, in __call__\n","      outputs = call_fn(inputs, *args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/layers/convolutional/base_conv.py\", line 250, in call\n","      outputs = self.convolution_op(inputs, self.kernel)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/layers/convolutional/base_conv.py\", line 232, in convolution_op\n","      name=self.__class__.__name__)\n","Node: 'my_model/efficientnetb3/block6f_expand_conv/Conv2D'\n","Detected at node 'my_model/efficientnetb3/block6f_expand_conv/Conv2D' defined at (most recent call last):\n","    File \"/gdrive/MyDrive/Colab Notebooks/main.py\", line 93, in <module>\n","      trainer.train(img, lab)\n","    File \"/gdrive/MyDrive/Colab Notebooks/utils/trainer.py\", line 48, in train\n","      preds: tf.Tensor = self._model(images, training=True)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/training.py\", line 490, in __call__\n","      return super().__call__(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py\", line 1014, in __call__\n","      outputs = call_fn(inputs, *args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/gdrive/MyDrive/Colab Notebooks/train/rjh/model/mymodel.py\", line 15, in call\n","      x = self.base(x)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/training.py\", line 490, in __call__\n","      return super().__call__(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py\", line 1014, in __call__\n","      outputs = call_fn(inputs, *args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py\", line 459, in call\n","      inputs, training=training, mask=mask)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py\", line 596, in _run_internal_graph\n","      outputs = node.layer(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py\", line 1014, in __call__\n","      outputs = call_fn(inputs, *args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n","      return fn(*args, **kwargs)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/layers/convolutional/base_conv.py\", line 250, in call\n","      outputs = self.convolution_op(inputs, self.kernel)\n","    File \"/usr/local/lib/python3.7/dist-packages/keras/layers/convolutional/base_conv.py\", line 232, in convolution_op\n","      name=self.__class__.__name__)\n","Node: 'my_model/efficientnetb3/block6f_expand_conv/Conv2D'\n","2 root error(s) found.\n","  (0) RESOURCE_EXHAUSTED:  OOM when allocating tensor with shape[52,1392,10,10] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n","\t [[{{node my_model/efficientnetb3/block6f_expand_conv/Conv2D}}]]\n","Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n","\n","\t [[assert_greater_equal/Assert/AssertGuard/pivot_f/_13/_7]]\n","Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n","\n","  (1) RESOURCE_EXHAUSTED:  OOM when allocating tensor with shape[52,1392,10,10] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n","\t [[{{node my_model/efficientnetb3/block6f_expand_conv/Conv2D}}]]\n","Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n","\n","0 successful operations.\n","0 derived errors ignored. [Op:__inference_train_32850]\n"]}]},{"cell_type":"code","source":[],"metadata":{"id":"YNG4W35gNYr9"},"execution_count":null,"outputs":[]}]}